// Quest card (NPC offer / turn-in; quests-story-ch1 5.3, save-ui-input 7.10; core-owned modal): one card per entry of the
// NPC (turn-ins first) with < n/N > navigation; name, badge, giver, type, the NPC's speech (offer / complete line),
// description, objectives, reward summary, fixed reward items, and on a turn-in card the pick-one gear generated by the
// core (selectable slots with tooltips). Accept -> CmdQuestAccept; Turn in -> CmdQuestTurnIn{choice} and the T17 chain
// offer; View story -> CmdDialogueOpenTree.
#pragma once

#include "CoreMinimal.h"

#include <string>

#include "UI/Panels/SAbyssPanelBase.h"

class SBox;

class SAbyssQuestCardPanel : public SAbyssPanelBase
{
public:
	SLATE_BEGIN_ARGS(SAbyssQuestCardPanel) {}
	SLATE_END_ARGS()

	void Construct(const FArguments& InArgs, const TSharedRef<FAbyssUiContext>& InContext, const std::string& InNpcId);

	virtual abyss::PanelId GetPanelId() const override { return abyss::PanelId::QuestCard; }
	virtual void Refresh(const abyss::Snapshot& Snap) override;
	virtual FVector2D GetDesignSize() const override { return FVector2D(420.0, Height); }
	virtual FVector2D GetDesignPosition() const override { return FVector2D(-1.0, -1.0); }
	virtual bool IsModal() const override { return true; }
	virtual float GetBackdropAlpha() const override { return 0.7f; }
	virtual std::string GetNpcId() const override { return NpcId; }

private:
	TSharedPtr<SBox> Content;
	std::string NpcId;
	std::string ShownQuest;
	int32 EntryIndex = 0;
	int32 Choice = -1;
	double Height = 400.0;
};
