#!/usr/bin/env python3
"""File lists for the Windows installers, generated from the staged Win64 build (unreal/CI/scripts/windows-installers.sh).

    gen_file_lists.py STAGED_DIR OUT_DIR

Writes into OUT_DIR:
    install-files.nsh     SetOutPath / File lines for every file (NSIS `!include`d by abyssfire.nsi)
    uninstall-files.nsh   Delete every installed file, then RMDir every directory deepest first (never RMDir /r:
                          a user who picked an existing folder as the install directory keeps their other files)
    file-list.txt         one relative path per line (wixl-heat input, sorted, '/' separators)
    size-kb.txt           total size in KiB (Add/Remove Programs EstimatedSize)

Paths are sorted so the generated installers are reproducible. Fails on names NSIS / MSI cannot carry.
"""
from __future__ import annotations

import sys
from pathlib import Path


def nsis_quote(s: str) -> str:
    """Quote a compile-time path (File source): makensis takes it literally except for ${define} references."""
    if '"' in s or "\n" in s or "${" in s:
        raise SystemExit(f"unsupported character sequence in path: {s!r}")
    return '"' + s + '"'


def nsis_instdir(rel: str) -> str:
    """Quote a runtime path below $INSTDIR (SetOutPath, Delete, RMDir): '$' in the name is escaped as '$$'."""
    nsis_quote(rel)
    win = rel.replace("/", "\\").replace("$", "$$")
    return '"$INSTDIR' + ("" if rel in ("", ".") else "\\" + win) + '"'


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src = Path(sys.argv[1]).resolve()
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    if not src.is_dir():
        raise SystemExit(f"{src} is not a directory")

    files = sorted((p for p in src.rglob("*") if p.is_file() or (p.is_symlink() and p.exists())),
                   key=lambda p: p.relative_to(src).as_posix().lower())
    if not files:
        raise SystemExit(f"{src} is empty")
    dirs = sorted({d for f in files for d in f.relative_to(src).parents if str(d) != "."},
                  key=lambda d: (-len(d.parts), d.as_posix().lower()))

    install = ["; generated by gen_file_lists.py - do not edit", f"; source: {src}"]
    current = None
    for f in files:
        rel = f.relative_to(src)
        parent = rel.parent
        if parent != current:
            install.append(f"SetOutPath {nsis_instdir(parent.as_posix())}")
            current = parent
        install.append(f"File {nsis_quote(f.as_posix())}")

    uninstall = ["; generated by gen_file_lists.py - do not edit"]
    for f in files:
        uninstall.append("Delete " + nsis_instdir(f.relative_to(src).as_posix()))
    for d in dirs:
        uninstall.append("RMDir " + nsis_instdir(d.as_posix()))

    total = sum(f.stat().st_size for f in files)
    (out / "install-files.nsh").write_text("\n".join(install) + "\n", encoding="utf-8")
    (out / "uninstall-files.nsh").write_text("\n".join(uninstall) + "\n", encoding="utf-8")
    (out / "file-list.txt").write_text("\n".join(f.relative_to(src).as_posix() for f in files) + "\n", encoding="utf-8")
    (out / "size-kb.txt").write_text(f"{(total + 1023) // 1024}\n", encoding="utf-8")
    print(f"{len(files)} files, {len(dirs)} directories, {total / 1048576:.1f} MiB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
