// Macro shim (compile-only, built with the tests): every public AbyssCore header compiled after the macros that UE,
// Windows, Apple and libc headers define in a game-module translation unit (ue58-platform.md 3.3 "no UE macro
// names"; Platform.h). A public header that names one of them - std::min(a, b) under windows.h's min(), a method
// called check() under UE's check(), an enumerator ERROR under wingdi.h - fails to compile here instead of in the
// Abyssfire module. Each macro expands to a stray '@', which is an error wherever it lands.
//
// Order mirrors a UE TU: the standard headers come first (CoreMinimal pulls them in before any core header), then the
// platform / engine macros, then every public core header (abyss_shim_public.h, generated by CMakeLists.txt) as the
// consumer side of a modular build (ABYSS_CORE_DLL=1 without ABYSS_CORE_BUILDING).
#include "abyss_shim_std.h"  // every <...> header the public headers include (generated)

#define ABYSS_SHIM_COLLISION @

// ---- Windows (windows.h without NOMINMAX / WIN32_LEAN_AND_MEAN, wingdi.h, winbase.h, wincon.h, rpcndr.h) ----------
#define min(...) ABYSS_SHIM_COLLISION
#define max(...) ABYSS_SHIM_COLLISION
#define near ABYSS_SHIM_COLLISION
#define far ABYSS_SHIM_COLLISION
#define NEAR ABYSS_SHIM_COLLISION
#define FAR ABYSS_SHIM_COLLISION
#define IN ABYSS_SHIM_COLLISION
#define OUT ABYSS_SHIM_COLLISION
#define OPTIONAL ABYSS_SHIM_COLLISION
#define CONST ABYSS_SHIM_COLLISION
#define VOID ABYSS_SHIM_COLLISION
#define TRUE ABYSS_SHIM_COLLISION
#define FALSE ABYSS_SHIM_COLLISION
#define ERROR ABYSS_SHIM_COLLISION
#define DELETE ABYSS_SHIM_COLLISION
#define IGNORE ABYSS_SHIM_COLLISION
#define INFINITE ABYSS_SHIM_COLLISION
#define NO_ERROR ABYSS_SHIM_COLLISION
#define ERROR_SUCCESS ABYSS_SHIM_COLLISION
#define MAX_PATH ABYSS_SHIM_COLLISION
#define CALLBACK ABYSS_SHIM_COLLISION
#define WINAPI ABYSS_SHIM_COLLISION
#define APIENTRY ABYSS_SHIM_COLLISION
#define PASCAL ABYSS_SHIM_COLLISION
#define CDECL ABYSS_SHIM_COLLISION
#define interface ABYSS_SHIM_COLLISION
#define small ABYSS_SHIM_COLLISION
#define hyper ABYSS_SHIM_COLLISION
#define ABSOLUTE ABYSS_SHIM_COLLISION
#define RELATIVE ABYSS_SHIM_COLLISION
#define TRANSPARENT ABYSS_SHIM_COLLISION
#define OPAQUE ABYSS_SHIM_COLLISION
#define ALTERNATE ABYSS_SHIM_COLLISION
#define WINDING ABYSS_SHIM_COLLISION
#define PASSTHROUGH ABYSS_SHIM_COLLISION
#define DIFFERENCE ABYSS_SHIM_COLLISION
#define MOUSE_MOVED ABYSS_SHIM_COLLISION
#define DOUBLE_CLICK ABYSS_SHIM_COLLISION
#define KEY_EVENT ABYSS_SHIM_COLLISION
#define MOUSE_EVENT ABYSS_SHIM_COLLISION
#define FOCUS_EVENT ABYSS_SHIM_COLLISION
#define MENU_EVENT ABYSS_SHIM_COLLISION
#define RGB(...) ABYSS_SHIM_COLLISION
#define FAILED(...) ABYSS_SHIM_COLLISION
#define SUCCEEDED(...) ABYSS_SHIM_COLLISION
#define CopyMemory(...) ABYSS_SHIM_COLLISION
#define ZeroMemory(...) ABYSS_SHIM_COLLISION
#define FillMemory(...) ABYSS_SHIM_COLLISION
#define MoveMemory(...) ABYSS_SHIM_COLLISION
#define GetCurrentTime(...) ABYSS_SHIM_COLLISION
#define Yield(...) ABYSS_SHIM_COLLISION
// A-/W- API aliases (object-like) that collide with ordinary method names.
#define GetObject ABYSS_SHIM_COLLISION
#define LoadImage ABYSS_SHIM_COLLISION
#define PlaySound ABYSS_SHIM_COLLISION
#define DrawText ABYSS_SHIM_COLLISION
#define TextOut ABYSS_SHIM_COLLISION
#define GetMessage ABYSS_SHIM_COLLISION
#define SendMessage ABYSS_SHIM_COLLISION
#define PostMessage ABYSS_SHIM_COLLISION
#define PeekMessage ABYSS_SHIM_COLLISION
#define DispatchMessage ABYSS_SHIM_COLLISION
#define MessageBox ABYSS_SHIM_COLLISION
#define CreateEvent ABYSS_SHIM_COLLISION
#define OpenEvent ABYSS_SHIM_COLLISION
#define ReportEvent ABYSS_SHIM_COLLISION
#define CreateMutex ABYSS_SHIM_COLLISION
#define CreateSemaphore ABYSS_SHIM_COLLISION
#define CreateFile ABYSS_SHIM_COLLISION
#define DeleteFile ABYSS_SHIM_COLLISION
#define CopyFile ABYSS_SHIM_COLLISION
#define MoveFile ABYSS_SHIM_COLLISION
#define CreateDirectory ABYSS_SHIM_COLLISION
#define RemoveDirectory ABYSS_SHIM_COLLISION
#define GetCurrentDirectory ABYSS_SHIM_COLLISION
#define SetCurrentDirectory ABYSS_SHIM_COLLISION
#define GetFileAttributes ABYSS_SHIM_COLLISION
#define GetTempPath ABYSS_SHIM_COLLISION
#define GetModuleFileName ABYSS_SHIM_COLLISION
#define LoadLibrary ABYSS_SHIM_COLLISION
#define FindResource ABYSS_SHIM_COLLISION
#define LoadString ABYSS_SHIM_COLLISION
#define UpdateResource ABYSS_SHIM_COLLISION
#define FormatMessage ABYSS_SHIM_COLLISION
#define OutputDebugString ABYSS_SHIM_COLLISION
#define GetCommandLine ABYSS_SHIM_COLLISION
#define GetEnvironmentVariable ABYSS_SHIM_COLLISION
#define SetEnvironmentVariable ABYSS_SHIM_COLLISION
#define GetUserName ABYSS_SHIM_COLLISION
#define GetClassName ABYSS_SHIM_COLLISION
#define RegisterClass ABYSS_SHIM_COLLISION
#define CreateWindow ABYSS_SHIM_COLLISION
#define FindWindow ABYSS_SHIM_COLLISION
#define GetWindowText ABYSS_SHIM_COLLISION
#define SetWindowText ABYSS_SHIM_COLLISION
#define CreateDialog ABYSS_SHIM_COLLISION
#define DialogBox ABYSS_SHIM_COLLISION
#define AppendMenu ABYSS_SHIM_COLLISION
#define InsertMenu ABYSS_SHIM_COLLISION
#define GetProp ABYSS_SHIM_COLLISION
#define SetProp ABYSS_SHIM_COLLISION
#define RemoveProp ABYSS_SHIM_COLLISION
#define EnumProps ABYSS_SHIM_COLLISION
#define CallWindowProc ABYSS_SHIM_COLLISION
#define MapVirtualKey ABYSS_SHIM_COLLISION
#define GetKeyNameText ABYSS_SHIM_COLLISION
#define CreateFont ABYSS_SHIM_COLLISION
#define EnumFonts ABYSS_SHIM_COLLISION
#define GetTextMetrics ABYSS_SHIM_COLLISION
#define StartDoc ABYSS_SHIM_COLLISION
#define GetDateFormat ABYSS_SHIM_COLLISION
#define GetTimeFormat ABYSS_SHIM_COLLISION
#define GetNumberFormat ABYSS_SHIM_COLLISION
#define CompareString ABYSS_SHIM_COLLISION
#define GetLocaleInfo ABYSS_SHIM_COLLISION
#define GetVersionEx ABYSS_SHIM_COLLISION
// MSVC <math.h> without __STDC__ (the default) and <stdlib.h> legacy names.
#define DOMAIN ABYSS_SHIM_COLLISION
#define SING ABYSS_SHIM_COLLISION
#define OVERFLOW ABYSS_SHIM_COLLISION
#define UNDERFLOW ABYSS_SHIM_COLLISION
#define TLOSS ABYSS_SHIM_COLLISION
#define PLOSS ABYSS_SHIM_COLLISION
#define HUGE ABYSS_SHIM_COLLISION

// ---- Unreal Engine (CoreMinimal.h and friends) ------------------------------------------------------------------------
#define check(...) ABYSS_SHIM_COLLISION
#define checkf(...) ABYSS_SHIM_COLLISION
#define checkSlow(...) ABYSS_SHIM_COLLISION
#define checkCode(...) ABYSS_SHIM_COLLISION
#define checkNoEntry(...) ABYSS_SHIM_COLLISION
#define checkNoReentry(...) ABYSS_SHIM_COLLISION
#define verify(...) ABYSS_SHIM_COLLISION
#define verifyf(...) ABYSS_SHIM_COLLISION
#define ensure(...) ABYSS_SHIM_COLLISION
#define ensureMsgf(...) ABYSS_SHIM_COLLISION
#define ensureAlways(...) ABYSS_SHIM_COLLISION
#define unimplemented(...) ABYSS_SHIM_COLLISION
#define TEXT(...) ABYSS_SHIM_COLLISION
#define LOCTEXT(...) ABYSS_SHIM_COLLISION
#define NSLOCTEXT(...) ABYSS_SHIM_COLLISION
#define INVTEXT(...) ABYSS_SHIM_COLLISION
#define UE_LOG(...) ABYSS_SHIM_COLLISION
#define UPROPERTY(...) ABYSS_SHIM_COLLISION
#define UFUNCTION(...) ABYSS_SHIM_COLLISION
#define UCLASS(...) ABYSS_SHIM_COLLISION
#define USTRUCT(...) ABYSS_SHIM_COLLISION
#define UENUM(...) ABYSS_SHIM_COLLISION
#define UMETA(...) ABYSS_SHIM_COLLISION
#define UPARAM(...) ABYSS_SHIM_COLLISION
#define UINTERFACE(...) ABYSS_SHIM_COLLISION
#define GENERATED_BODY(...) ABYSS_SHIM_COLLISION
#define GENERATED_UCLASS_BODY(...) ABYSS_SHIM_COLLISION
#define GENERATED_USTRUCT_BODY(...) ABYSS_SHIM_COLLISION
#define PURE_VIRTUAL(...) ABYSS_SHIM_COLLISION
#define ARRAY_COUNT(...) ABYSS_SHIM_COLLISION
#define UE_ARRAY_COUNT(...) ABYSS_SHIM_COLLISION
#define STRUCT_OFFSET(...) ABYSS_SHIM_COLLISION
#define LIKELY(...) ABYSS_SHIM_COLLISION
#define UNLIKELY(...) ABYSS_SHIM_COLLISION
#define UE_LIKELY(...) ABYSS_SHIM_COLLISION
#define UE_UNLIKELY(...) ABYSS_SHIM_COLLISION
#define DEPRECATED(...) ABYSS_SHIM_COLLISION
#define UE_DEPRECATED(...) ABYSS_SHIM_COLLISION
#define ENUM_CLASS_FLAGS(...) ABYSS_SHIM_COLLISION
#define ENUM_RANGE_BY_COUNT(...) ABYSS_SHIM_COLLISION
#define DECLARE_DELEGATE(...) ABYSS_SHIM_COLLISION
#define DECLARE_MULTICAST_DELEGATE(...) ABYSS_SHIM_COLLISION
#define DECLARE_LOG_CATEGORY_EXTERN(...) ABYSS_SHIM_COLLISION
#define DEFINE_LOG_CATEGORY(...) ABYSS_SHIM_COLLISION
#define TCHAR_TO_UTF8(...) ABYSS_SHIM_COLLISION
#define UTF8_TO_TCHAR(...) ABYSS_SHIM_COLLISION
#define SCOPE_CYCLE_COUNTER(...) ABYSS_SHIM_COLLISION
#define QUICK_SCOPE_CYCLE_COUNTER(...) ABYSS_SHIM_COLLISION
#define TRACE_CPUPROFILER_EVENT_SCOPE(...) ABYSS_SHIM_COLLISION
#define GET_MEMBER_NAME_CHECKED(...) ABYSS_SHIM_COLLISION
#define UE_NONCOPYABLE(...) ABYSS_SHIM_COLLISION
#define PI ABYSS_SHIM_COLLISION
#define HALF_PI ABYSS_SHIM_COLLISION
#define TWO_PI ABYSS_SHIM_COLLISION
#define INV_PI ABYSS_SHIM_COLLISION
#define SMALL_NUMBER ABYSS_SHIM_COLLISION
#define KINDA_SMALL_NUMBER ABYSS_SHIM_COLLISION
#define BIG_NUMBER ABYSS_SHIM_COLLISION
#define EULERS_NUMBER ABYSS_SHIM_COLLISION
#define DELTA ABYSS_SHIM_COLLISION
#define MAX_FLT ABYSS_SHIM_COLLISION
#define FLOAT_NORMAL_THRESH ABYSS_SHIM_COLLISION
#define UE_PI ABYSS_SHIM_COLLISION
#define UE_HALF_PI ABYSS_SHIM_COLLISION
#define UE_TWO_PI ABYSS_SHIM_COLLISION
#define UE_DOUBLE_PI ABYSS_SHIM_COLLISION
#define UE_SMALL_NUMBER ABYSS_SHIM_COLLISION
#define UE_KINDA_SMALL_NUMBER ABYSS_SHIM_COLLISION
#define UE_BIG_NUMBER ABYSS_SHIM_COLLISION
#define UE_DELTA ABYSS_SHIM_COLLISION
#define MIN_uint8 ABYSS_SHIM_COLLISION
#define MIN_uint16 ABYSS_SHIM_COLLISION
#define MIN_uint32 ABYSS_SHIM_COLLISION
#define MIN_uint64 ABYSS_SHIM_COLLISION
#define MIN_int8 ABYSS_SHIM_COLLISION
#define MIN_int16 ABYSS_SHIM_COLLISION
#define MIN_int32 ABYSS_SHIM_COLLISION
#define MIN_int64 ABYSS_SHIM_COLLISION
#define MAX_uint8 ABYSS_SHIM_COLLISION
#define MAX_uint16 ABYSS_SHIM_COLLISION
#define MAX_uint32 ABYSS_SHIM_COLLISION
#define MAX_uint64 ABYSS_SHIM_COLLISION
#define MAX_int8 ABYSS_SHIM_COLLISION
#define MAX_int16 ABYSS_SHIM_COLLISION
#define MAX_int32 ABYSS_SHIM_COLLISION
#define MAX_int64 ABYSS_SHIM_COLLISION
#define MIN_flt ABYSS_SHIM_COLLISION
#define MAX_flt ABYSS_SHIM_COLLISION
#define MIN_dbl ABYSS_SHIM_COLLISION
#define MAX_dbl ABYSS_SHIM_COLLISION
#define INDEX_NONE ABYSS_SHIM_COLLISION
#define DLLEXPORT ABYSS_SHIM_COLLISION
#define DLLIMPORT ABYSS_SHIM_COLLISION
#define FORCEINLINE ABYSS_SHIM_COLLISION
#define FORCENOINLINE ABYSS_SHIM_COLLISION
#define FORCEINLINE_DEBUGGABLE ABYSS_SHIM_COLLISION
#define RESTRICT ABYSS_SHIM_COLLISION
#define CONSTEXPR ABYSS_SHIM_COLLISION
#define ABSTRACT ABYSS_SHIM_COLLISION
#define LINE_TERMINATOR ABYSS_SHIM_COLLISION
#define UE_NODISCARD ABYSS_SHIM_COLLISION
#define CORE_API ABYSS_SHIM_COLLISION
#define ENGINE_API ABYSS_SHIM_COLLISION
#define ABYSSCORE_API ABYSS_SHIM_COLLISION  // UBT's own export macro for the AbyssCore module (Platform.h: not used)
#define ABYSSFIRE_API ABYSS_SHIM_COLLISION

// ---- Apple (AssertMacros.h, objc.h), GCC GNU-mode predefines --------------------------------------------------------
#define require(...) ABYSS_SHIM_COLLISION
#define require_noerr(...) ABYSS_SHIM_COLLISION
#define require_action(...) ABYSS_SHIM_COLLISION
#define check_noerr(...) ABYSS_SHIM_COLLISION
#define verify_noerr(...) ABYSS_SHIM_COLLISION
#define nil ABYSS_SHIM_COLLISION
#define Nil ABYSS_SHIM_COLLISION
#define YES ABYSS_SHIM_COLLISION
#define NO ABYSS_SHIM_COLLISION
#define DEBUG ABYSS_SHIM_COLLISION
#define linux ABYSS_SHIM_COLLISION
#define unix ABYSS_SHIM_COLLISION

#include "abyss_shim_public.h"  // every Public/abyss/**/*.h (generated)

// The headers must leave the consumer's macros alone (no #undef of someone else's macro).
#if !defined(min) || !defined(max) || !defined(check) || !defined(verify) || !defined(PI) || !defined(TEXT) || \
    !defined(ERROR) || !defined(DELETE)
#error "an AbyssCore public header #undef'd a platform / engine macro"
#endif

namespace abyss::shim {
// Odr-use something from the core so the TU is not empty.
inline constexpr int kShimApiVersion = kCoreApiVersion;
}  // namespace abyss::shim
